// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomMatch.Models;

namespace RoomMatch.Migrations
{
    [DbContext(typeof(RoomMatchContext))]
    partial class RoomMatchContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("RoomMatch.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("A1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("A2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("A3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("A4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("A5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("A6")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("A7")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("A8")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("A9")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
